### ISSUE TITLE
Add Nextstrain automation docs

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/pathogen-repo-guide#10]
In addition to ["Getting started" docs](https://github.com/nextstrain/pathogen-repo-template/issues/9), we should have documentation on how to set up Nextstrain specific automation.

This should include docs on 
- [ ] setting up CI with [pathogen-repo-ci](https://github.com/nextstrain/.github/blob/master/.github/workflows/pathogen-repo-ci.yaml)
- [ ] adding pathogen repos to the [infra repo](https://github.com/nextstrain/infra/blob/main/env/production/locals.tf#L10) to use short-lived AWS credentials
- [ ] setting up automated builds with [pathogen-repo-build](https://github.com/nextstrain/.github/blob/master/.github/workflows/pathogen-repo-build.yaml)

**Comment by tsibley** [comment]
> setting up AWS credentials for running builds on AWS Batch and/or uploading files and deploying builds to AWS S3 (this would be simplified once we https://github.com/nextstrain/.github/pull/53)

I would go as far to say that we shouldn't embark on setting up new AWS creds for automation going forward and should require using the OIDC provider with AWS role assumption. I've done most of the work already and real world use will help refine it, ultimately making it very smooth to use and much easier for us to manage/operate.
