### ISSUE TITLE
Add standard CI jobs for ingest workflow

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/pathogen-repo-guide#21]
The pathogen-repo-ci has been used for a while now for testing the phylogenetic workflow. We should have a similar CI workflow for the ingest workflow as they become a standard part of the pathogen workflows. 

I don't think we want to the run the **full** ingest of all NCBI data for the CI workflow. Should this mimic the phylogenetic workflow and start the workflow from example data instead of downloading from NCBI? I think it would make sense to start from an example NCBI zip archive that we keep in version control. 

I'd think the CI workflow would only test the core ingest workflow. The Nextstrain automation profile rules can be tested manually as we've done in the past.

**Comment by tsibley** [comment]
+1. I'd suggest adding ingest CI as _jobs_ in the existing pathogen-repo-ci workflow, rather than making a new separate ingest CI workflow which we have to promulgate everywhere.

**Comment by joverlee521** [comment]
With https://github.com/nextstrain/.github/issues/89, we are leaving the details of how the ingest CI workflow should work on a per pathogen repo basis. The ingest workflow is just required to have a `build-configs/ci/config.yaml` config file for running the CI workflow.
