### ISSUE TITLE
Provide a no-curation option for NCBI Ingest

### ISSUE THREAD

**Issue by j23414** [nextstrain/pathogen-repo-guide#30]
### Context

Inspired by [a review comment of the measles/add-ingest pull request](https://github.com/nextstrain/measles/pull/10#discussion_r1466896144), propose an optional rule for skipping (or bypassing) curation steps to produce raw outcomes. These outcomes can then guide the selection of specific curation steps or metadata field transformations.

This idea is loosely connected to the effort of standardizing NCBI field transformations, as discussed in [https://github.com/nextstrain/pathogen-repo-guide/issues/20](https://github.com/nextstrain/pathogen-repo-guide/issues/20).

### Description

Allow users to initiate ingest to produce an **uncurated** `metadata.tsv` file, from which they can compare against the **curated** `metadata.tsv` file. Users can then decide which curation steps to opt-in for or choose to use our defaults. 

### Possible solution

One potential approach includes utilizing the "custom_rules" config in the Snakefile. Users can then import "no-curate" rules that take [data/ncbi.ndjson](https://github.com/nextstrain/pathogen-repo-guide/blob/fae3951b5001bc479a9c2f095441a99e9ebf827a/ingest/rules/curate.smk#L59) , pass it through [augur curate passthru](https://github.com/nextstrain/pathogen-repo-guide/blob/fae3951b5001bc479a9c2f095441a99e9ebf827a/ingest/rules/curate.smk#L111-L115) , and generate an uncurated `metadata.tsv` file.

**Comment by joverlee521** [comment]
I'm not sure we would need custom rules here...

It should be enough to document the NCBI Datasets output target `data/ncbi_dataset_report.tsv` so that users can inspect the raw data there.
