### ISSUE TITLE
Add pre-commit-config.yaml, pre-commit GHA, and cleanup existing files

### ISSUE THREAD

**Issue by genehack** [nextstrain/pathogen-repo-guide#42]
Essentially recapitulate https://github.com/nextstrain/seasonal-cov/issues/9 in this repo.

**Comment by victorlin** [comment]
I opened https://github.com/nextstrain/measles/issues/56 to apply this to that repo, which adopted pathogen-repo-guide before pre-commit was added. Not sure if it's worth doing the same for other repos (I would think yes).
