### ISSUE TITLE
Missing comma in `fetch_ncbi_dataset_package` rule causing syntax error

### ISSUE THREAD

**Issue by BryanTegomoh** [nextstrain/pathogen-repo-guide#58]
### Current Behavior
The `fetch_ncbi_dataset_package` rule in the `Snakefile` has a syntax error due to a missing comma at the end of the `benchmark` line. This causes the workflow to fail.

### Expected Behavior
The workflow should run without syntax errors.

### How to reproduce
Steps to reproduce the current behavior:
1. Open the repository.
2. Run the `nextstrain build ingest` command, with any pathogen ncbi taxon id and corresponding entrez search term. 
3. Observe the syntax error in the terminal output. In my case, the error appeared here: 
```
Error in rule fetch_ncbi_dataset_package:
    jobid: 4
    output: data/ncbi_dataset.zip
    shell:

        datasets download virus genome taxon 35511             --no-progressbar             --filename data/ncbi_dataset.zip

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

### Possible solution
Add a comma at the end of the `benchmark` line in the `fetch_ncbi_dataset_package` rule.

**Current Code**:
```python
benchmark:
    "benchmarks/fetch_ncbi_dataset_package.txt"
shell:
    """
    datasets download virus genome taxon {params.ncbi_taxon_id:q} \
    --no-progressbar \
    --filename {output.dataset_package}
    """

**Corrected Code**:

benchmark:
    "benchmarks/fetch_ncbi_dataset_package.txt",
shell:
    """
    datasets download virus genome taxon {params.ncbi_taxon_id:q} \
    --no-progressbar \
    --filename {output.dataset_package}
    """

I am using Windows OS

**Comment by joverlee521** [comment]
Sorry you're running into an error @BryanTegomoh!

I don't think this is a syntax error. The [Snakemake benchmark](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#benchmark-rules) does not require a trailing comma. If this was a Snakemake syntax error, you should see an error similar to 
```
SyntaxError in file /nextstrain/build/ingest/rules/fetch_from_ncbi.smk, line 115:
invalid syntax. Perhaps you forgot a comma?
```

Seems like something went wrong during the download from NCBI, but I cannot replicate the error. 
Can you try running the workflow again? It might just be a temporary issue with NCBI `datasets` command.

**Comment by BryanTegomoh** [comment]
Thank you @joverlee521. Removing the comma reproduces the error on my terminal. I am using Powershell terminal in Windows OS. Adding the comma appears to resolve the error. If it helps, I am running the Jamestown Canyon virus (`ncbi taxon id: "35511", entrez_search_term: "txid35511"`). 

Attached corresponding log file. 
[2024-07-25T232508.421771.snakemake.log](https://github.com/user-attachments/files/16384442/2024-07-25T232508.421771.snakemake.log)

**Comment by joverlee521** [comment]
I'm trying to figure out if it's just a coincidence that one of the retries didn't fail when you added the comma.

Could you try removing the line 

https://github.com/nextstrain/pathogen-repo-guide/blob/89b3c5dbc9b8f6a009f4a19c3ac56113bc5511ee/ingest/rules/fetch_from_ncbi.smk#L45

Then share your log files for running with and without the comma? 

Additionally, it'd be helpful to know what Nextstrain runtime version you are using. Can you provide the output of `nextstrain version --verbose`?

**Comment by BryanTegomoh** [comment]
Removing line 45 works `retries: 5` . See attached log file without the comma. 
[2024-07-26T200020.971694.snakemake.log](https://github.com/user-attachments/files/16396235/2024-07-26T200020.971694.snakemake.log)

Adding the comma, does not reproduce the error with line 45 removed. 
[2024-07-26T200915.936367.snakemake.log](https://github.com/user-attachments/files/16396325/2024-07-26T200915.936367.snakemake.log)

Thank you

**Comment by joverlee521** [comment]
Thanks @BryanTegomoh, that helps me confirm that the comma fixing the error was purely a coincidence and this is not a syntax error.

The underlying cause was either an internet connection issue or a transient error with the `datasets` command. If you run into a similar error again, I suggest waiting a few minutes before re-running the workflow to avoid running into NCBI rate limits.
