### ISSUE TITLE
Adding ingest guide to documentation

### ISSUE THREAD

**Issue by miparedes** [nextstrain/pathogen-repo-guide#61]
It'd be great for future pathogen builders if the [ingest guide](https://docs.nextstrain.org/en/latest/tutorials/creating-a-pathogen-repo/creating-an-ingest-workflow.html) and the information about how to work on the repo with things like [pre-commit](https://github.com/nextstrain/ingest/tree/main?tab=readme-ov-file#working-on-this-repo) would also be included in this repo for ease!

**Comment by joverlee521** [comment]
Thanks for the reminder @miparedes! I'll link the top level README to the Nextstrain docs and add a section about pre-commit.
