### ISSUE TITLE
ingest: Add example build-config/ci/config.yaml

### ISSUE THREAD

**Issue by genehack** [nextstrain/pathogen-repo-guide#71]
>> Snakemake requires at least one top level key in a config file, so including a bogus key here that should not be used anywhere in the Snakemake workflow
>
> More precisely, Snakemake requires a YAML file with a top-level map/dict/object type. It may be empty; keys are not required.
> 
> We could avoid the bogus config key above by using flow syntax for a map (`{}`) instead, e.g.
> 
> ```yaml
> # TODO: If the ingest workflow ever runs too long, we should figure out a way
> # to subset the ingest data. Currently, the CI just runs the default ingest workflow.
> {}
> ```
>
> The bogus config key also got propagated to [measles](https://github.com/nextstrain/measles/commit/fdf1b705fd0a83b97d01d58938e9ecdcc6e042be), [rabies](https://github.com/nextstrain/rabies/commit/d04cd77ab11adee4c1ee520e4edd8dd74613a322), and [oropouche](https://github.com/nextstrain/oropouche/commit/7d95ba474394f1cb067180e3e8b4794576d5417d), and seems likely to propagate further over time. It'd be nice to avoid, IMO. 

 _Originally posted by @tsibley in [44f27a5](https://github.com/nextstrain/zika/commit/44f27a5670e391b4a5df93ba56d08e2d99fa415c#commitcomment-148494298)_

**Comment by joverlee521** [comment]
Consolidated with https://github.com/nextstrain/pathogen-repo-guide/issues/56
